name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Verify Build Artifacts
        run: ls -la build/libs

      - name: Build Docker Image
        run: docker build -t myapp:latest .
