name: CI/CD Pipeline

on:
  push:
    branches:
      - qurban

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set Execute Permissions for gradlew
      - name: Set Execute Permissions
        run: chmod +x ./gradlew

      # 3. Build Application (Skipping Tests)
      - name: Build Java Application
        run: ./gradlew clean build -x test

      # 4. Debug Build Directory
      - name: Debug Build Directory
        run: ls -R build/libs

      # 5. Docker Image Build
      - name: Build Docker Image
        run: |
          JAR_FILE=$(ls build/libs/*.jar)
          echo "Jar file: $JAR_FILE"
          cp $JAR_FILE myapp.jar
          docker build -t myapp:latest .
          docker save myapp:latest > myapp.tar

      # 6. Deploy to Server
      - name: Deploy to Local Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LOCAL_SERVER_IP }}
          username: ${{ secrets.LOCAL_SERVER_USER }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker load < /path/to/myapp.tar
            docker run -d --name myapp -p 8080:8080 myapp:latest
