name: CI/CD Pipeline

on:
  push:
    branches:
      - qurban

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodunuzu Checkout Edin
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Gradle ile Derleme (Testleri Skip Et)
      - name: Build Java Application
        run: ./gradlew clean build -x test

      # 3. Docker Image'i Hazırlayın
      - name: Prepare Docker Build
        run: |
          cp build/libs/*.jar myapp.jar
          docker build -t myapp:latest .
          docker save myapp:latest > myapp.tar

      # 4. Yerel Sunucuya Deploy Edin
      - name: Deploy to Local Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.LOCAL_SERVER_IP }}
          username: ${{ secrets.LOCAL_SERVER_USER }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker load < /path/to/myapp.tar
            docker run -d --name myapp -p 8080:8080 myapp:latest
