name: Deploy Docker App to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Reponuzu Klonlayın
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Uygulamayı Build Edin
      - name: Build Jar
        run: mvn clean package

       # 4. Docker Hub'a Giriş Yapın
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker Image'ı Docker Hub'a Push Edin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
