name: Deploy to Local Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Reponuzu Klonlayın
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Docker Image'ı Build Edin
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      # 3. Local Server'a SSH ile Bağlanıp Deploy Edin
      - name: Deploy to Local Server
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.LOCAL_SERVER_IP }}
          username: ${{ secrets.LOCAL_SERVER_USER }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker load < /path/to/myapp.tar
            docker run -d --name myapp -p 8080:8080 myapp:latest
